GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/user/count
Accept: application/json