server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: route-user
          uri: http://localhost:8001
          predicates:
            - Path=/user-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: 'true'
            maxAge: '3600'