server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: route-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: 'true'
            maxAge: '3600'